resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
replica: 3
ingress:
  enabled: false

service:
  enabled: true
  type: LoadBalancer
  port: 80
  targetPort: 3000
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-attributes: load_balancing.cross_zone.enabled=true
    service.beta.kubernetes.io/aws-load-balancer-name: metric-grafana
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-0777b68e7af4f9dae"
    service.beta.kubernetes.io/aws-load-balancer-target-group-attributes: stickiness.enabled=false
    service.beta.kubernetes.io/load-balancer-source-ranges: 0.0.0.0/0
    external-dns.alpha.kubernetes.io/hostname: "metric_grafana.kuberix.co.kr"

persistence:
  type: pvc
  enabled: true
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  size: 10Gi
  # annotations: {}
  finalizers:
    - kubernetes.io/pvc-protection

adminUser: admin
adminPassword: kuberix